### ISSUE TITLE
ByteSource generation

### ISSUE THREAD

**Issue by AkatQuas** [Nihiue/little-byte#2]
https://github.com/Nihiue/little-byte/blob/8496960392a676e61df3615ef7867f217543dbe1/src/compiler/index.ts#L24-L28

As far as I'm concerned, this source code generation could be replaced with only code length repetition.

```ts
const sourceMap = _module.wrap(' '.repeat(code.length));
```

It works very well.

But, it would break the test script. 

Just FYI.

**Comment by Nihiue** [comment]
loader generates  blank dummy code if bytesource not found

https://github.com/Nihiue/little-byte/blob/8496960392a676e61df3615ef7867f217543dbe1/src/loader/index.ts#L27

But also thanks for comment

**Comment by AkatQuas** [comment]
I did not realize that how strong you are until I read about [this issue](https://github.com/bytenode/bytenode/issues/157).

You are very 🐮🍺, bro.
